create extension if not exists pgcrypto;

create table if not exists public.teachers (
    teacher_id bigint generated by default as identity primary key,
    username text not null unique,
    password text not null,
    name text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.students (
    student_id bigint generated by default as identity primary key,
    name text not null,
    face_embedding jsonb,
    voice_embedding jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.subjects (
    subject_id bigint generated by default as identity primary key,
    subject_code text not null unique,
    name text not null,
    section text not null,
    teacher_id bigint not null references public.teachers (teacher_id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.subject_students (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students (student_id) on delete cascade,
    subject_id bigint not null references public.subjects (subject_id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (student_id, subject_id)
);

create table if not exists public.attendance_logs (
    attendance_id bigint generated by default as identity primary key,
    student_id bigint not null references public.students (student_id) on delete cascade,
    subject_id bigint not null references public.subjects (subject_id) on delete cascade,
    timestamp timestamptz not null default now(),
    is_present boolean not null default false
);

alter table public.teachers enable row level security;
alter table public.students enable row level security;
alter table public.subjects enable row level security;
alter table public.subject_students enable row level security;
alter table public.attendance_logs enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies where schemaname = 'public' and tablename = 'teachers' and policyname = 'allow all teachers'
    ) then
        create policy "allow all teachers"
        on public.teachers
        for all
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies where schemaname = 'public' and tablename = 'students' and policyname = 'allow all students'
    ) then
        create policy "allow all students"
        on public.students
        for all
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies where schemaname = 'public' and tablename = 'subjects' and policyname = 'allow all subjects'
    ) then
        create policy "allow all subjects"
        on public.subjects
        for all
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies where schemaname = 'public' and tablename = 'subject_students' and policyname = 'allow all subject_students'
    ) then
        create policy "allow all subject_students"
        on public.subject_students
        for all
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies where schemaname = 'public' and tablename = 'attendance_logs' and policyname = 'allow all attendance_logs'
    ) then
        create policy "allow all attendance_logs"
        on public.attendance_logs
        for all
        using (true)
        with check (true);
    end if;
end $$;
